# Generated by Django 6.0.7 on 2026-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_best_effort_top_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resting_hr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
