# Generated by Django 6.0.7 on 2026-08-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='append_match_date_to_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rename_matched_activities',
            field=models.BooleanField(default=False),
        ),
    ]
