# Generated by Django 6.0.7 on 2026-08-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_append_match_date_to_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='copy_matched_workout_tags',
            field=models.BooleanField(default=False),
        ),
    ]
