# Generated by Django 6.0.7 on 2026-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_copy_matched_workout_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threshold_sanity_pct',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='threshold_window_days',
            field=models.PositiveSmallIntegerField(default=112),
        ),
    ]
