# Generated by Django 6.0.7 on 2026-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_threshold_sanity_pct_user_threshold_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ftp_calculation_method',
            field=models.CharField(choices=[('twenty_min_test', '20-minute test (best 20-min power x 0.95)'), ('sixty_min_direct', '60-minute direct (best 60-min power)')], default='twenty_min_test', max_length=20),
        ),
    ]
