# Generated by Django 6.0.7 on 2026-08-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='delegated_athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
