# Generated by Django 6.0.7 on 2026-08-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_personalaccesstoken_delegated_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='running_power_source',
            field=models.CharField(choices=[('stryd', 'Stryd'), ('native', 'Native (e.g. Garmin Running Power)')], default='stryd', max_length=10),
        ),
    ]
