# Generated by Django 6.0.7 on 2026-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_running_power_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lap_source',
            field=models.CharField(choices=[('matched_workout', 'Matched workout'), ('original', 'Original (FIT file)')], default='matched_workout', max_length=20),
        ),
    ]
