# Generated by Django 6.1.1 on 2026-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_lap_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threshold_warning_days',
            field=models.PositiveSmallIntegerField(choices=[(14, '14 days'), (21, '21 days'), (28, '28 days'), (0, 'Off')], default=21),
        ),
    ]
