# Generated by Django 6.1.1 on 2026-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_threshold_warning_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decoupling_if_limit',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_min_steady_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_vi_limit_bike',
            field=models.FloatField(default=1.06),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_vi_limit_run',
            field=models.FloatField(default=1.04),
        ),
    ]
