# Generated by Django 6.1.1 on 2026-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_decoupling_if_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decoupling_hot_air_temp',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_hot_skin_temp',
            field=models.FloatField(default=34.0),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_warm_air_temp',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='user',
            name='decoupling_warm_skin_temp',
            field=models.FloatField(default=33.0),
        ),
    ]
