# Generated by Django 6.1.1 on 2026-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_decoupling_hot_air_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_shoe_limit_km',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
