# Generated by Django 6.1.1 on 2026-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_default_shoe_limit_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="decoupling_use_workout_warmup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="decoupling_warmup_minutes",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
