# Generated by Django 5.0.9 on 2026-06-17 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('heart_rate', 'Heart rate'), ('bike_power', 'Bike power'), ('run_power', 'Run power'), ('pace', 'Pace')], max_length=20)),
                ('zones', models.JSONField(default=list)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='zoneset',
            constraint=models.UniqueConstraint(fields=('athlete', 'type'), name='unique_athlete_zone_type'),
        ),
    ]
