# Generated by Django 6.0.7 on 2026-08-13 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_threshold_checked'),
        ('athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ftp', 'FTP'), ('critical_run_power', 'Critical running power'), ('threshold_pace', 'Threshold pace')], max_length=20)),
                ('value_numeric', models.PositiveIntegerField(blank=True, null=True)),
                ('value_pace', models.CharField(blank=True, default='', max_length=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_history', to=settings.AUTH_USER_MODEL)),
                ('source_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_history', to='activities.activity')),
            ],
            options={
                'verbose_name_plural': 'threshold history',
                'indexes': [models.Index(fields=['athlete', 'field', 'effective_from'], name='athletes_th_athlete_3a54b8_idx')],
            },
        ),
    ]
