# Generated by Django 6.0.7 on 2026-08-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_remove_activity_critical_run_power_snapshot_and_more'),
        ('athletes', '0002_thresholdhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdhistory',
            name='source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_history', to='activities.activity'),
        ),
    ]
