# Generated by Django 6.0.7 on 2026-08-15 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_thresholdhistory_source_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestEffortRecomputeJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('kind', models.CharField(blank=True, choices=[('cycling_hr', 'Cycling heart rate'), ('cycling_power', 'Cycling power'), ('running_hr', 'Running heart rate'), ('running_pace', 'Running pace'), ('running_power', 'Running power')], default='', max_length=20)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('processed_items', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_effort_recompute_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
