# Generated by Django 6.1.1 on 2026-10-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_backfill_heat_strain_core_skin_temp_stats'),
        ('athletes', '0006_thresholdhistory_current_from_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedThresholdCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ftp', 'FTP'), ('critical_run_power', 'Critical running power'), ('threshold_pace', 'Threshold pace')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_threshold_candidates', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_threshold_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'accepted threshold candidates',
                'constraints': [models.UniqueConstraint(fields=('athlete', 'field', 'activity'), name='unique_accepted_threshold_candidate')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdSuggestionDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ftp', 'FTP'), ('critical_run_power', 'Critical running power'), ('threshold_pace', 'Threshold pace')], max_length=20)),
                ('kind', models.CharField(choices=[('rejected', 'Rejected'), ('upcoming_drop', 'Upcoming drop')], max_length=20)),
                ('key', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_suggestion_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'threshold suggestion dismissals',
                'constraints': [models.UniqueConstraint(fields=('athlete', 'field', 'kind', 'key'), name='unique_threshold_suggestion_dismissal')],
            },
        ),
    ]
