# Generated by Django 5.0.9 on 2026-06-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('bike', 'Bike'), ('run', 'Run'), ('swim', 'Swim'), ('walk', 'Walk')], max_length=10)),
                ('environment', models.CharField(choices=[('outdoor', 'Outdoor'), ('indoor', 'Indoor')], default='outdoor', max_length=10)),
                ('has_gps', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('moving_time', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('distance_source', models.CharField(choices=[('gps', 'GPS'), ('footpod', 'Footpod'), ('trainer', 'Trainer'), ('manual', 'Manual')], default='gps', max_length=10)),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('norm_power', models.IntegerField(blank=True, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('tss', models.IntegerField(default=0)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('ascent', models.IntegerField(blank=True, null=True)),
                ('start_weight_kg', models.FloatField(blank=True, null=True)),
                ('end_weight_kg', models.FloatField(blank=True, null=True)),
                ('fluids_ml', models.IntegerField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='gear.bike')),
                ('shoe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='gear.shoe')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='workouts.workout')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='activities.activity')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tags', to='activities.activity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tags', to='activities.tag')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', through='activities.ActivityTag', to='activities.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('athlete', 'name'), name='unique_athlete_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='activitytag',
            constraint=models.UniqueConstraint(fields=('activity', 'tag'), name='unique_activity_tag'),
        ),
    ]
