# Generated by Django 5.0.9 on 2026-06-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cycling_power', 'Cycling power'), ('running_pace', 'Running pace'), ('running_power', 'Running power')], max_length=20)),
                ('window', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_efforts', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_efforts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'window'],
            },
        ),
        migrations.CreateModel(
            name='DurationCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('power', 'Power'), ('heartrate', 'Heart rate')], max_length=10)),
                ('extends_to', models.IntegerField()),
                ('points', models.JSONField(default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_curves', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField()),
                ('ts', models.DateTimeField()),
                ('power', models.IntegerField(blank=True, null=True)),
                ('heartrate', models.IntegerField(blank=True, null=True)),
                ('cadence', models.IntegerField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='activities.activity')),
            ],
            options={
                'ordering': ['t'],
            },
        ),
        migrations.AddConstraint(
            model_name='besteffort',
            constraint=models.UniqueConstraint(fields=('athlete', 'kind', 'window'), name='unique_athlete_kind_window'),
        ),
        migrations.AddConstraint(
            model_name='durationcurve',
            constraint=models.UniqueConstraint(fields=('activity', 'metric'), name='unique_activity_curve_metric'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('activity', 'ts'), name='unique_activity_record_ts'),
        ),
    ]
