import datetime

from django.db import migrations


def _month_add(d: datetime.date, months: int) -> datetime.date:
    """d must already be the first of its month. Returns the first of the month
    `months` months later (or earlier, for a negative value)."""
    total = d.year * 12 + (d.month - 1) + months
    return datetime.date(total // 12, total % 12 + 1, 1)


def _partition_statements() -> list[str]:
    """One CREATE TABLE ... PARTITION OF statement per calendar month, covering 10
    years back through 6 months forward from whenever this migration actually runs
    (computed at apply time - Django re-imports migration modules on every `migrate`
    invocation, so datetime.date.today() here reflects the real run date, not whenever
    this file was authored), plus a DEFAULT partition as a safety net for anything
    outside that range (very old imported data, clock skew) so an insert can never
    hard-fail for lacking a matching partition. A scheduled task (see
    activities/tasks.py) keeps rolling the forward end of this range ahead over time."""
    today = datetime.date.today()
    start = datetime.date(today.year - 10, today.month, 1)
    end = _month_add(datetime.date(today.year, today.month, 1), 7)  # +6 months, +1 for the loop's exclusive bound

    statements = []
    cur = start
    while cur < end:
        nxt = _month_add(cur, 1)
        name = f"activities_record_p{cur.strftime('%Y%m')}"
        statements.append(
            f"CREATE TABLE {name} PARTITION OF activities_record "
            f"FOR VALUES FROM ('{cur.isoformat()}T00:00:00+00') TO ('{nxt.isoformat()}T00:00:00+00');"
        )
        cur = nxt
    statements.append("CREATE TABLE activities_record_default PARTITION OF activities_record DEFAULT;")
    return statements


class Migration(migrations.Migration):
    """Creates activities_record as a natively partitioned table (RANGE on `ts`,
    monthly partitions) instead of a TimescaleDB hypertable - timescaledb isn't
    supported on AWS RDS/Aurora (verified against AWS's own docs; see
    AWS_MIGRATION_PLAN.md §4), and the app's actual Timescale usage was already just
    the partitioning itself - no compression policies, no continuous aggregates, no
    time_bucket() queries anywhere in either backend.

    activities_record has to be dropped and recreated rather than altered in place -
    Postgres requires PARTITION BY to be set at CREATE TABLE time, it can't be added
    to an existing table. Safe here because this runs immediately after 0002 creates
    the (still-empty) plain table, in the same migration sequence - there's no data to
    preserve at this point. Only recreates the columns that exist as of 0002; 0004's
    later ADD COLUMN operations apply to the new partitioned parent - and automatically
    cascade to every partition - exactly as they did against the old hypertable, no
    changes needed there.

    Also fixes a real gap: activities_record previously had NO primary key at all (the
    original version of this migration dropped the surrogate `id` PK - Timescale
    requires the partition column in any unique/PK constraint, which `id` alone didn't
    satisfy - and replaced it with only a non-unique index on `id`). Native declarative
    partitioning has the same requirement, so this version adds an explicit
    PRIMARY KEY (activity_id, ts) - the same uniqueness guarantee the model's
    UniqueConstraint (unique_activity_record_ts) already declared, just enforced by a
    real PK now instead of a separately-named constraint, matching the Java backend's
    `record` table exactly (it already has this same composite PK).
    """

    dependencies = [
        ("activities", "0002_besteffort_durationcurve_record_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TABLE activities_record;",
                "CREATE TABLE activities_record ("
                "  id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
                "  activity_id VARCHAR(40) NOT NULL REFERENCES activities_activity (id) ON DELETE CASCADE,"
                "  t INTEGER NOT NULL,"
                "  ts TIMESTAMPTZ NOT NULL,"
                "  power INTEGER,"
                "  heartrate INTEGER,"
                "  cadence INTEGER,"
                "  altitude DOUBLE PRECISION,"
                "  lat DOUBLE PRECISION,"
                "  lng DOUBLE PRECISION,"
                "  speed DOUBLE PRECISION,"
                "  distance_km DOUBLE PRECISION,"
                "  PRIMARY KEY (activity_id, ts)"
                ") PARTITION BY RANGE (ts);",
                "CREATE INDEX activities_record_id_idx ON activities_record (id);",
                *_partition_statements(),
            ],
            reverse_sql=[
                "SELECT 1;",
            ],
        ),
    ]
