# Generated by Django 5.0.9 on 2026-06-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_record_hypertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_air_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='air_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='core_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='heat_strain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='skin_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
