# Generated by Django 6.0.6 on 2026-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_activity_avg_air_temp_activity_avg_humidity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="aerobic_training_effect",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="anaerobic_training_effect",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="training_effect_label",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
