# Generated by Django 6.0.6 on 2026-07-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_aerobic_training_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='parent_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_activities', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('bike', 'Bike'), ('run', 'Run'), ('swim', 'Swim'), ('walk', 'Walk'), ('multisport', 'Multisport'), ('transition', 'Transition')], max_length=10),
        ),
    ]
