# Generated by Django 6.0.6 on 2026-07-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_parent_activity_alter_activity_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='primary_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_activities', to='activities.activity'),
        ),
    ]
