# Generated by Django 6.0.6 on 2026-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_primary_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='device',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
