# Generated by Django 6.0.7 on 2026-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('bike', 'Bike'), ('run', 'Run'), ('swim', 'Swim'), ('walk', 'Walk'), ('row', 'Row'), ('multisport', 'Multisport'), ('transition', 'Transition')], max_length=10),
        ),
    ]
