# Generated by Django 6.0.7 on 2026-07-30 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_besteffort_unique_athlete_kind_window_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_left_balance_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(blank=True, help_text='kcal', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_max',
            field=models.IntegerField(blank=True, help_text='metres', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_min',
            field=models.IntegerField(blank=True, help_text='metres', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_speed',
            field=models.FloatField(blank=True, help_text='km/h', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_descent',
            field=models.IntegerField(blank=True, help_text='metres', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trimp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='besteffort',
            name='kind',
            field=models.CharField(choices=[('cycling_hr', 'Cycling heart rate'), ('cycling_power', 'Cycling power'), ('running_hr', 'Running heart rate'), ('running_pace', 'Running pace'), ('running_power', 'Running power')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
