# Generated by Django 6.0.7 on 2026-08-11 18:39
# See 0013_backfill_activity_threshold_snapshots for the data migration that seeds
# ftp_snapshot/critical_run_power_snapshot/threshold_pace_snapshot on existing rows.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_avg_cadence_activity_avg_left_balance_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='critical_run_power_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ftp_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_critical_run_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_ftp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_threshold_pace',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='threshold_pace_snapshot',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
