# Generated by Django 6.0.7 on 2026-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_backfill_activity_threshold_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='threshold_checked',
            field=models.BooleanField(default=False),
        ),
    ]
