# Generated by Django 6.0.7 on 2026-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_threshold_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='critical_run_power_snapshot',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='ftp_snapshot',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='suggested_critical_run_power',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='suggested_ftp',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='suggested_threshold_pace',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='threshold_checked',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='threshold_pace_snapshot',
        ),
    ]
