# Generated by Django 6.0.7 on 2026-08-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_remove_activity_critical_run_power_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activities.activitycomment'),
        ),
    ]
