# Generated by Django 6.0.7 on 2026-08-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activitycomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='power_source',
            field=models.CharField(blank=True, choices=[('stryd', 'Stryd'), ('native', 'Native')], default='', max_length=10),
        ),
    ]
