# Generated by Django 6.0.7 on 2026-09-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activity_power_source'),
        ('workouts', '0004_workoutstep_power_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='repeat_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='workout_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laps', to='workouts.workoutstep'),
        ),
    ]
