# Generated by Django 6.1.1 on 2026-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_lap_repeat_index_lap_workout_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_core_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_heat_strain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_skin_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_core_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_heat_strain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_skin_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
