# Generated by Django 6.1.1 on 2026-10-04 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_backfill_heat_strain_core_skin_temp_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='decoupling_avg_core',
            field=models.FloatField(blank=True, help_text='Core °C over the steady window', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_avg_temp',
            field=models.FloatField(blank=True, help_text='Air °C over the steady window', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_halves',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_hr_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_if',
            field=models.FloatField(blank=True, help_text='Intensity factor: NP / threshold at date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_power_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_vi',
            field=models.FloatField(blank=True, help_text='Variability index: NP / avg power', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ef_first',
            field=models.FloatField(blank=True, help_text='W/bpm', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ef_second',
            field=models.FloatField(blank=True, help_text='W/bpm', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='steady_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityDurability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('bike', 'Bike'), ('run', 'Run')], max_length=10)),
                ('basis', models.CharField(choices=[('kj', 'Kilojoules'), ('minutes', 'Minutes')], max_length=10)),
                ('threshold', models.IntegerField()),
                ('window_s', models.IntegerField()),
                ('power', models.IntegerField(help_text='W')),
                ('start_offset_s', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durability_rows', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durability_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity durability rows',
                'indexes': [models.Index(fields=['athlete', 'sport', 'activity_date'], name='activities__athlete_233a9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'threshold', 'window_s'), name='unique_activity_durability')],
            },
        ),
    ]
