# Generated by Django 6.1.1 on 2026-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activity_decoupling_avg_core_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='decoupling_avg_skin',
            field=models.FloatField(blank=True, help_text='Skin °C over the steady window', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='decoupling_warm',
            field=models.BooleanField(default=False),
        ),
    ]
