# Generated by Django 5.0.9 on 2026-06-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_besteffort_durationcurve_record_and_more'),
        ('gear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('on_duplicate', models.CharField(choices=[('skip', 'Skip'), ('replace', 'Replace')], default='skip', max_length=10)),
                ('status', models.CharField(choices=[('unpacking', 'Unpacking'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='unpacking', max_length=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('stored_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='queued', max_length=12)),
                ('progress', models.FloatField(default=0.0)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('weight_before_kg', models.FloatField(blank=True, null=True)),
                ('weight_after_kg', models.FloatField(blank=True, null=True)),
                ('fluids_ml', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='gear.shoe')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='uploads.uploadbatch')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
