# Generated by Django 6.0.6 on 2026-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped')], default='queued', max_length=12),
        ),
    ]
