FIELD_SPECS = {
    "hr": {"num": True, "label": "avg HR", "unit": "bpm"},
    "maxhr": {"num": True, "label": "max HR", "unit": "bpm"},
    "tss": {"num": True, "label": "TSS", "unit": ""},
    "distance": {"num": True, "label": "distance", "unit": "km"},
    "duration": {"num": True, "label": "duration", "unit": "min"},
    "power": {"num": True, "label": "power", "unit": "W"},
    "pace": {"num": True, "label": "pace", "unit": "/km"},
    "sport": {"num": False, "label": "sport"},
    "environment": {"num": False, "label": "environment"},
    "name": {"num": False, "label": "name"},
    "tag": {"num": False, "label": "tag"},
}

FIELD_ALIASES = {
    "hr": "hr",
    "bpm": "hr",
    "heartrate": "hr",
    "avghr": "hr",
    "hravg": "hr",
    "maxhr": "maxhr",
    "hrmax": "maxhr",
    "tss": "tss",
    "load": "tss",
    "stress": "tss",
    "distance": "distance",
    "dist": "distance",
    "km": "distance",
    "kms": "distance",
    "duration": "duration",
    "time": "duration",
    "mins": "duration",
    "minutes": "duration",
    "power": "power",
    "watts": "power",
    "watt": "power",
    "np": "power",
    "pace": "pace",
    "sport": "sport",
    "type": "sport",
    "discipline": "sport",
    "name": "name",
    "title": "name",
    "environment": "environment",
    "env": "environment",
    "tag": "tag",
}

ENVIRONMENT_VALUES = {
    "indoor": "indoor",
    "indoors": "indoor",
    "treadmill": "indoor",
    "trainer": "indoor",
    "turbo": "indoor",
    "outdoor": "outdoor",
    "outdoors": "outdoor",
    "outside": "outdoor",
}

SPORT_VALUES = {
    "run": "run",
    "runs": "run",
    "running": "run",
    "ride": "bike",
    "rides": "bike",
    "bike": "bike",
    "bikes": "bike",
    "biking": "bike",
    "cycling": "bike",
    "cycle": "bike",
    "swim": "swim",
    "swims": "swim",
    "swimming": "swim",
}

UNIT_FIELDS = {
    "bpm": "hr",
    "km": "distance",
    "kms": "distance",
    "w": "power",
    "watt": "power",
    "watts": "power",
    "tss": "tss",
    "min": "duration",
    "mins": "duration",
    "minute": "duration",
    "minutes": "duration",
}

STOP_WORDS = {
    "show",
    "all",
    "me",
    "my",
    "the",
    "that",
    "those",
    "this",
    "are",
    "a",
    "an",
    "find",
    "get",
    "give",
    "list",
    "where",
    "with",
    "please",
    "workout",
    "workouts",
    "activity",
    "activities",
    "session",
    "sessions",
    "of",
    "i",
    "have",
    "had",
    "did",
    "for",
    "to",
    "it",
    "then",
    "only",
    "any",
    "longer",
    "shorter",
}
