# Generated by Django 6.0.7 on 2026-07-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0008_activity_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('sport', models.CharField(blank=True, choices=[('bike', 'Bike'), ('run', 'Run'), ('swim', 'Swim'), ('multisport', 'Multisport')], default='', max_length=10)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('goal_time', models.DurationField(blank=True, null=True)),
                ('result_time', models.DurationField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result', to='activities.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
