# Generated by Django 6.0.7 on 2026-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
