# Generated by Django 6.0.7 on 2026-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledworkout',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
