# Generated by Django 5.0.9 on 2026-06-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(blank=True, choices=[('road', 'Road'), ('indoor', 'Indoor'), ('gravel', 'Gravel'), ('tt', 'Time trial')], default='', max_length=10)),
                ('groupset', models.CharField(blank=True, default='', max_length=150)),
                ('distance_km', models.IntegerField(default=0)),
                ('hours', models.FloatField(default=0)),
                ('rides', models.IntegerField(default=0)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('km', models.IntegerField(default=0)),
                ('limit_km', models.IntegerField()),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='gear.bike')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, choices=[('replaced', 'Replaced'), ('cleaned', 'Cleaned'), ('inspected', 'Inspected'), ('adjusted', 'Adjusted')], default='', max_length=10)),
                ('reset', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='gear.component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeModelVersion',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gear.shoemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('colourway', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('km', models.IntegerField(default=0)),
                ('limit_km', models.IntegerField(default=0)),
                ('since', models.DateField(auto_now_add=True)),
                ('retired', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to=settings.AUTH_USER_MODEL)),
                ('shoe_model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoes', to='gear.shoemodelversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoe',
            constraint=models.UniqueConstraint(fields=('athlete', 'name'), name='unique_athlete_shoe_name'),
        ),
    ]
