# Generated by Django 6.1.1 on 2026-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_shoemodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemodelversion',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
