# Generated by Django 6.1.1 on 2026-10-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_alter_shoemodelversion_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoePhoto',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('taken_on', models.DateField()),
                ('km', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gear.shoe')),
            ],
            options={
                'ordering': ['taken_on', 'created'],
            },
        ),
    ]
