# Generated by Django 5.0.9 on 2026-06-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('bike', 'Bike'), ('run', 'Run')], max_length=10)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('tss', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('warmup', 'Warmup'), ('block', 'Block'), ('rec', 'Recovery'), ('cool', 'Cooldown')], max_length=10)),
                ('end_type', models.CharField(choices=[('time', 'Time'), ('distance', 'Distance'), ('manual', 'Manual')], max_length=10)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('target_pct', models.FloatField(blank=True, null=True)),
                ('repeat', models.IntegerField(default=1)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workouts.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
