# Generated by Django 6.0.7 on 2026-07-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutstep',
            name='target_pct',
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workouts.workoutstep'),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target2_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target2_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target2_type',
            field=models.CharField(choices=[('cadence', 'Cadence'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target_type',
            field=models.CharField(blank=True, choices=[('power', 'Power'), ('hr', 'Heart rate'), ('pace', 'Pace'), ('cadence', 'Cadence'), ('open', 'Open')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutstep',
            name='end_type',
            field=models.CharField(blank=True, choices=[('time', 'Time'), ('distance', 'Distance'), ('manual', 'Manual')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutstep',
            name='kind',
            field=models.CharField(choices=[('warmup', 'Warmup'), ('block', 'Block'), ('rec', 'Recovery'), ('cool', 'Cooldown'), ('repeat', 'Repeat')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='workoutstep',
            constraint=models.UniqueConstraint(fields=('workout', 'parent', 'order'), name='unique_step_order_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='workoutstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('distance__isnull', True), ('duration__isnull', True), ('end_type', ''), ('kind', 'repeat'), ('target_type', '')), models.Q(('kind', 'repeat'), _negated=True), _connector='OR'), name='repeat_step_has_no_leaf_fields'),
        ),
    ]
