# Generated by Django 6.0.7 on 2026-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_chart_preview_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutstep',
            name='power_unit',
            field=models.CharField(blank=True, choices=[('pct_ftp', '% FTP'), ('watts', 'Watts')], default='pct_ftp', max_length=10),
        ),
    ]
