# Generated by Django 6.0.7 on 2026-09-10 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_lap_repeat_index_lap_workout_step'),
        ('workouts', '0004_workoutstep_power_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutMatchScan',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('total_candidates', models.IntegerField(blank=True, null=True)),
                ('processed_candidates', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scans', to='workouts.workout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutMatchScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.FloatField()),
                ('duration_diff_seconds', models.IntegerField()),
                ('coverage', models.FloatField()),
                ('implied_ftp', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.activity')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='workouts.workoutmatchscan')),
            ],
            options={
                'ordering': ['-correlation'],
            },
        ),
    ]
