# Generated by Django 6.0.7 on 2026-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutmatchscan_workoutmatchscancandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmatchscan',
            name='excluded_step_kinds',
            field=models.JSONField(default=list),
        ),
    ]
