# Generated by Django 6.1.1 on 2026-10-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutmatchscan_excluded_step_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmatchscan',
            name='duration_basis',
            field=models.CharField(choices=[('time', 'Time'), ('distance', 'Distance')], default='time', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutmatchscancandidate',
            name='distance_diff_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
