# Generated by Django 6.1.1 on 2026-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workoutmatchscan_duration_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmatchscan',
            name='smooth_power',
            field=models.BooleanField(default=False),
        ),
    ]
