# Generated by Django 6.1.1 on 2026-10-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workoutmatchscan_smooth_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmatchscan',
            name='correlation_basis',
            field=models.CharField(choices=[('power', 'Power'), ('laps', 'Laps')], default='power', max_length=10),
        ),
    ]
