# Generated by Django 6.0.7 on 2026-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('equipment', 'Equipment'), ('workouts', 'Workouts'), ('activities', 'Activities'), ('races', 'Races'), ('scheduled_workouts', 'Scheduled workouts')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='importjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('equipment', 'Equipment'), ('workouts', 'Workouts'), ('activities', 'Activities'), ('races', 'Races'), ('scheduled_workouts', 'Scheduled workouts')], default='', max_length=20),
        ),
    ]
