# Generated by Django 6.0.7 on 2026-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexport', '0002_exportjob_current_step_importjob_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='processed_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='total_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='processed_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='total_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
