# Generated by Django 6.0.7 on 2026-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexport', '0003_exportjob_processed_items_exportjob_total_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='threshold_history_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('equipment', 'Equipment'), ('workouts', 'Workouts'), ('activities', 'Activities'), ('races', 'Races'), ('scheduled_workouts', 'Scheduled workouts'), ('threshold_history', 'Threshold history')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('equipment', 'Equipment'), ('workouts', 'Workouts'), ('activities', 'Activities'), ('races', 'Races'), ('scheduled_workouts', 'Scheduled workouts'), ('threshold_history', 'Threshold history')], default='', max_length=20),
        ),
    ]
